# Generated by Django 4.2.7 on 2026-03-18 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guest_house', '0001_initial'),
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_bookings', to='travel.trip'),
        ),
        migrations.AddField(
            model_name='room',
            name='guesthouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='guest_house.guesthouse'),
        ),
        migrations.AddField(
            model_name='laundryservice',
            name='guesthouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laundries', to='guest_house.guesthouse'),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='guesthouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchens', to='guest_house.guesthouse'),
        ),
        migrations.AddField(
            model_name='cook',
            name='guesthouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooks', to='guest_house.guesthouse'),
        ),
        migrations.AddField(
            model_name='contact',
            name='guesthouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='guest_house.guesthouse'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('guesthouse', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='laundryservice',
            unique_together={('guesthouse', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='kitchen',
            unique_together={('guesthouse', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='cook',
            unique_together={('guesthouse', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('guesthouse', 'phone')},
        ),
    ]
