# Generated by Django 4.2.7 on 2026-03-18 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclebooking',
            name='trip',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_bookings', to='travel.trip'),
        ),
        migrations.AddField(
            model_name='vehiclebooking',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='fleet.vehicle'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='fleet.fleethub'),
        ),
        migrations.AddField(
            model_name='driver',
            name='hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='fleet.fleethub'),
        ),
    ]
