# Generated by Django 6.0.3 on 2026-03-23 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the application using this key', max_length=100)),
                ('masked_key', models.CharField(default='', help_text='Masked key for display', max_length=50)),
                ('encrypted_key', models.TextField(default='', help_text='Encrypted key for retrieval')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rate_limit', models.IntegerField(default=60, help_text='Requests per minute')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('allowed_endpoints', models.JSONField(blank=True, default=list, help_text='List of allowed URL patterns')),
                ('permissions', models.JSONField(blank=True, default=dict, help_text="Method-level permissions e.g. {'dashboard': ['GET']}")),
            ],
            options={
                'verbose_name': 'Internal Access Key',
                'verbose_name_plural': 'Internal Access Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIKeyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'API Key History',
                'verbose_name_plural': 'API Key Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, help_text='Application Name or User ID', max_length=100, null=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('latency_ms', models.FloatField(help_text='Response time in milliseconds')),
            ],
            options={
                'verbose_name': 'API Log',
                'verbose_name_plural': 'API Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DynamicEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for the endpoint', max_length=100)),
                ('url_path', models.CharField(help_text='The path segment. Final URL will be /api/connect/<url_path>/', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('response_type', models.CharField(choices=[('NONE', 'Ingestion Only (Receive Data)'), ('TRIP_LIST', 'Return: Trip List'), ('TRIP_STATS', 'Return: Trip Statistics'), ('CUSTOM_SCRIPT', 'Custom Script (Python/SQL)')], default='NONE', max_length=20)),
                ('response_config', models.JSONField(blank=True, default=dict, help_text='Configuration for response data (e.g. filters)')),
                ('script_type', models.CharField(blank=True, choices=[('PYTHON', 'Python'), ('SQL', 'SQL')], max_length=10, null=True)),
                ('script_content', models.TextField(blank=True, help_text='Python script or SQL query')),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='external_api_key', max_length=50, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
            },
        ),
        migrations.CreateModel(
            name='DynamicSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(help_text='The JSON payload received')),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api_management.dynamicendpoint')),
            ],
            options={
                'verbose_name': 'API Log',
                'verbose_name_plural': 'API Logs',
                'ordering': ['-received_at'],
            },
        ),
    ]
