# Generated by Django 4.2.7 on 2026-03-13 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='e.g. ADMINISTRATIVE, Grade A', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('external_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('location_type', models.CharField(max_length=50)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('parent_id', models.CharField(blank=True, max_length=50, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('route_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_ending_here', to='travel_masters.location')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_starting_here', to='travel_masters.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoutePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('path_name', models.CharField(help_text='e.g., Via NH-44', max_length=255)),
                ('via_locations', models.JSONField(default=list, help_text='Ordered list of location IDs')),
                ('is_default', models.BooleanField(default=False)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='travel_masters.route')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TollGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('gate_code', models.CharField(blank=True, help_text='Auto-generated 4-digit gate code', max_length=4, null=True, unique=True)),
                ('registered_id', models.CharField(blank=True, help_text='Manual Registered ID', max_length=50, null=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('gps_coordinates', models.CharField(blank=True, max_length=100)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user')),
                ('location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel_masters.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TollRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('travel_mode', models.CharField(max_length=50)),
                ('journey_type', models.CharField(default='UP', help_text='UP, DOWN, or TO_AND_FRO', max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user')),
                ('toll_gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='travel_masters.tollgate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoutePathToll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toll_assignments', to='travel_masters.routepath')),
                ('toll_gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_masters.tollgate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FuelRateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('rate_per_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user')),
            ],
            options={
                'unique_together': {('state', 'vehicle_type', 'is_deleted')},
            },
        ),
        migrations.CreateModel(
            name='EligibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(help_text='Accommodation, Daily Allowance, Flight, Train, Bus, Local Conveyance, Mileage Rate', max_length=50)),
                ('city_type', models.CharField(blank=True, help_text='Metro, Non-Metro, State HQ, Districts, Others, N/A', max_length=50, null=True)),
                ('limit_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Max eligible amount. 0 if not applicable.', max_digits=10)),
                ('eligibility_class', models.CharField(blank=True, help_text='Economy, II A/c, Sleeper, N/A', max_length=50, null=True)),
                ('cadre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_rules', to='travel_masters.cadre')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user')),
            ],
            options={
                'ordering': ['cadre__name', 'category', 'city_type'],
                'unique_together': {('cadre', 'category', 'city_type', 'is_deleted')},
            },
        ),
    ]
